### ISSUE TITLE
support a list of unsafe commands

### ISSUE THREAD

**Issue by alaypatel07** [rumstead/kubectl-safe#23]
Thanks for this awesome plugin. 

I was wondering a `KUBECTL_UNSAFE_COMMANDS` variable can be supported.

The need I have is to only block delete command, and I do not want to keep my list up to date anytime a new command is added to kubectl

**Comment by rumstead** [comment]
Definitely!

**Comment by rumstead** [comment]
@alaypatel07  can you confirm it works as expected? Then I will publish the new version.

**Comment by alaypatel07** [comment]
@rumstead thanks for the quick turnaround, I will test it and get back to you.

**Comment by alaypatel07** [comment]
Hi @rumstead https://github.com/rumstead/kubectl-safe/pull/24#pullrequestreview-1010935594 added my verification to the PRR. Before you cut a new release, can you please look at #25 and let me know what you think? Thanks!
